### PR TITLE
GP2-1347, GP2-1348 Compare markets - tabs enhancements

### PR DESCRIPTION
**Pull request by bobmeredith**
This PR adds a number of changes and enhancements to the population and economy tabs of the compare markets page.
Changes in number formatting mean that we are now using raw, unformatted values from directory-api and formating on the client. Additional fields are added to return the totals of ranking fields to display.
Additionally, the year of the fields is being shown.  A base year (the most common value amongst the data on a tab) is calculated and displayed below the table. Any fields that do not have the same year as this, have the year displayed on the field.

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-1347 https://uktrade.atlassian.net/browse/GP2-1348
- [x] Jira ticket has the correct status.
- [x] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [x] Explains how to test locally, including how to set up appropriate data
- [x] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [x] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Comment by bobmeredith** [comment]
image

image

**Comment by bobmeredith** [comment]
Testing - check tab data and format from a variety of country/ HS code combinations.

**Review by rafa-garcia — APPROVED** [review]
LGTM

**Comment by dahfool** [comment]
normaliseValues and millify 👍🏿

**Pull request merged**
