### PR TITLE
GP2-2707 - EP missing link on Costs and Pricing page

### PR DESCRIPTION
**Pull request by bobmeredith**
Adds link on Export plan - costs and pricing page.

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-2707
- [x] Jira ticket has the correct status.
- [x] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [x] Explains how to test locally, including how to set up appropriate data
- [x] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
Testing: Check the link.  It should open in new tab.
Same as link on 'adapting your product' page

**Review by webbyfox — APPROVED** [review]
LGTM

**Review by depsiatwal — APPROVED** [review]
LGTM

**Pull request merged**
