### PR TITLE
Add hidden span for UKEA video transcript

### PR DESCRIPTION
**Pull request by davidu1975**
Add hidden span for UKEA video transcript 

as "View Video transcript for <event name> recording"

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/KLS-1794
- [x] Jira ticket has the correct status.
- [x] A clear/description pull request messaged added.

### Housekeeping

- [x] Python requirements have been re-compiled.
- [x] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Comment by boxadesign** [comment]
@davidu1975 Does the event_video.html template also need the `event.name` passed into `render_video`?

**Comment by boxadesign** [comment]
@davidu1975 Does the event_video.html template also need the `event.name` passed into `render_video`?

**Review by lewis-coulson-dit — APPROVED** [review]
LGTM

**Comment by davidu1975** [comment]
> @davidu1975 Does the event_video.html template also need the `event.name` passed into `render_video`?

well spotted

**Pull request merged**
