### PR TITLE
GP2-502 Suggested Markets

### PR DESCRIPTION
**Pull request by bobmeredith**
- [x] Ticket exists in Jira  https://uktrade.atlassian.net/browse/GP2-502 
 - [x] Jira ticket has the correct status.
 - [x] [Changelog](CHANGELOG.md) entry added.

 - [x] (if is a UI change) Includes screenshot(s) - ideally before and after, but at least after
 - [x] (if needs manual testing) How to test locally, including how to set up appropriate data
 
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
Before product selected
image

**Comment by bobmeredith** [comment]
Testing.
Choose 'Add country' before selecting a product. Suggested markets section should show message and button.
Select a product. Open market selector and confirm that markets are the set relevant to the hs2 part of the product code selected. Change product and check that the suggested markets update.

**Review by webbyfox — COMMENTED** [review]
@bobmeredith overall looks good. The only comment I've is when you don't have a product selected and click on the country chooser model. it asked you `add product` which not doing anything at the moment when you click.

**Review by webbyfox — APPROVED** [review]
LGTM

**Pull request merged**
