### PR TITLE
create adaptation for target market page

### PR DESCRIPTION
**Pull request by dahfool**
To do (delete all that do not apply):

 - [x] Change has a jira ticket that has the correct status.
 - [x] Changelog entry added.

### CODE REVIEW

**Comment by dahfool** [comment]
> will need to add tests :-)

**Comment by dahfool** [comment]
> will need to add tests :-)

For the view ?

**Comment by depsiatwal** [comment]
yeah any python code will need tests else codecov fails
you can see under unit/tests. test_views classes

**Comment by depsiatwal** [comment]
it might already be covered as codecov hasn't detected a drop actaully

**Comment by dahfool** [comment]
> it might already be covered as codecov hasn't detected a drop actaully

🤷‍♂️

**Pull request merged**
