### PR TITLE
amend the hero_text_si fields to read hero_text_signedin etc

### PR DESCRIPTION
**Pull request by Rambowalsh**
(Please add a sentence or two explaining the context of this PR. Reviewers can go to the ticket for detail.)
CONTEXT: This changeset adds/removes/updates [summary of feature/area/code] so that [summary of benefit].

_Tick or delete as appropriate:_

### Workflow

- [ x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-1839
- [x ] Jira ticket has the correct status.
- [ ] [Changelog](CHANGELOG.md) entry added. - all part of the original changelog entry

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]
Seems fine to me 👍

**Comment by webbyfox** [comment]
@Rambowalsh FYI @stevejalim There are model changes and you are editing existing migration - This might cause an issue. Please run make migrations

**Review by webbyfox — CHANGES_REQUESTED** [review]
See comment above

**Comment by stevejalim** [comment]
@webbyfox yeah, good catch - you're right. 

@Rambowalsh I think if you revert the changes to the existing migration 0024 and add a new one, that'd be the way forward

**Comment by Rambowalsh** [comment]
Ok changes made as per comments

**Review by stevejalim — APPROVED** [review]
👍  but you'll also need a re-review from @webbyfox to clear the Github block on merging

**Review by webbyfox — APPROVED** [review]

**Pull request merged**
