### PR TITLE
GP2-589_add_export_plan_context_to_dashboard

### PR DESCRIPTION
**Pull request by bobmeredith**
- [x] Ticket exists in Jira  https://uktrade.atlassian.net/browse/GP2-589
 - [x] Jira ticket has the correct status.
 - [x] [Changelog](CHANGELOG.md) entry added.

 - [x] (if needs manual testing) How to test locally, including how to set up appropriate data
 
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Comment by bobmeredith** [comment]
Manual testing - just check that personalization bar shows correctly (when logged in) on the export plan dashboard page like all other pages and shows correctly, the selected product and market.

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
Testing- ensure the personalization bar is populated on the export plan dashboard page and that the product/country can be changed and that the changes persist over a page reload.

**Review by depsiatwal — APPROVED** [review]
LGTM I was going to do this tomorrow :-)

**Pull request merged**
