### PR TITLE
GP2-759_product_finder_No_result

### PR DESCRIPTION
**Pull request by bobmeredith**
- [x] Ticket exists in Jira  https://uktrade.atlassian.net/browse/GP2-759
 - [x] Jira ticket has the correct status.
 - [x] [Changelog](CHANGELOG.md) entry added.

 - [x] (if is a UI change) Includes screenshot(s) - ideally before and after, but at least after
 - [x] (if needs manual testing) How to test locally, including how to set up appropriate data
 - [ ] (if adding feature flags) Cleaned up old flags
 
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
Testing - bring up the 'no results' page by putting any random string in the search box that doesn't match anything.

**Comment by bobmeredith** [comment]
To neable user research on 15/16 October 2020 added a feature flag FEATURE_ENABLE_PRODUCT_SEARCH_WHEN_NO_USER
Set this flag to True in environment to force the personalisation bar to display even when user is logged out.

**Comment by webbyfox** [comment]
@bobmeredith  did we needed to merge this? I thought we could deploy this branch as plan B?

**Comment by bobmeredith** [comment]
It's a feature flag so no harm in the main branch.  Can tidy up after the UR if it's not needed.

**Pull request merged**
