### PR TITLE
private@digital.trade.gov.uk -> great.support@trade.gov.uk

### PR DESCRIPTION
**Pull request by logikblok**
Changed email to align to support inbox

image

 - [X] Ticket exists in Jira  https://uktrade.atlassian.net/browse/GP2-875
 - [X] Jira ticket has the correct status.
 - [X] (if is a UI change) Includes screenshot(s) - ideally before and after, but at least after
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Review by stevejalim — CHANGES_REQUESTED** [review]
Looks good to me, but just spotted a note from Santosh in JIRA

> Can you please add Sign up page as well, email address needs to change.

**Comment by webbyfox** [comment]
shall we add an email address variable in the setting that can be used where ever it needed?

**Comment by stevejalim** [comment]
> shall we add an email address variable in the setting that can be used where ever it needed?

yeah, that's worth doing - a setting and a context processor, perhaps?

**Comment by webbyfox** [comment]
I've added new env to all three envs in vault

**Review by bobmeredith — APPROVED** [review]
Looks good to me

**Comment by stevejalim** [comment]
@logikblok Looks good to me, thanks 

But do we also need to act on this from Santosh in the JIRA ticket?

> Can you please add Sign up page as well, email address needs to change.

or does that single template cover Sign up already?

**Comment by webbyfox** [comment]
yes, it's basically a different template but the same code

**Review by stevejalim — APPROVED** [review]
LGTM! Thanks for the fixups

**Pull request merged**
