### PR TITLE
Greatuk 20 alter warning message on events listing page

### PR DESCRIPTION
**Pull request by FoxJamie16**
User experience change - 

- Refactors warning text to make it less prevalent and remove warning icon.
- Add media icon to draw attention to video hyperlink. 

_Tick or delete as appropriate:_

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GREATUK-20
- [x] Jira ticket has the correct status.
- [x] A clear/description pull request messaged added.

### Reviewing help

- [x] Explains how to test locally, including how to set up appropriate data
- [x] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [x] Ran the `make manage download_geolocation_data` command
- [x] Frontend assets have been re-compiled.
- [x] I have checked that my PR is using the latest package versions of: great-components, directory-constants, directory-healthcheck, directory-validators, directory-components, directory-api-client, directory-ch-client, django-staff-sso-client, directory-forms-api-client, directory-sso-api-client, sigauth

after
before

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

### CODE REVIEW

**Review by timothyPatterson — DISMISSED** [review]
LGTM so long as designer has reviewed and OK'd.

**Comment by FoxJamie16** [comment]
> LGTM so long as designer has reviewed and OK'd.

Sounds great thanks very much for reviewing, I'll check with Chris and merge when approved.

**Comment by FoxJamie16** [comment]
Icon altered following designer review and link styling added to keep alignment with icon. New screenshot added here showing current version, awaiting dev and designer approval for merge. 
uktrade-20 post-refactor

**Comment by FoxJamie16** [comment]
All works in staging. 
staging

**Comment by FoxJamie16** [comment]
Screenshot post warning message styling change:
greatuk-20 post warning style

**Comment by FoxJamie16** [comment]
Passed user design review, requesting dev re-review as both event_list_recording_details.html and export-academy.scss have been altered since earlier review.

**Review by stuart-mindt — APPROVED** [review]
LGTM

**Pull request merged**
