### PR TITLE
Gp2 836 country modal fixes

### PR DESCRIPTION
**Pull request by bobmeredith**
- [x] Ticket exists in Jira  https://uktrade.atlassian.net/browse/GP2-836 
 - [x] Jira ticket has the correct status.
 - [x] [Changelog](CHANGELOG.md) entry added.

 - [x] (if is a UI change) Includes screenshot(s) - ideally before and after, but at least after
 - [x] (if needs manual testing) How to test locally, including how to set up appropriate data
 
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)
 
 Contains a load of es-lint fixes too.

### CODE REVIEW

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
Testing - there were bugs in the relation between the expanders and filter that meant, if the user typed a filter, then removed it - it wouldn't actually remove the filter and left the expanders in a messy state.
This should be fixed now, as should the visual defects on expanders.
Also, the scroll area of the modal should cover the entire modal with the close button floating.

**Review by webbyfox — APPROVED** [review]
LGTM

**Pull request merged**
