### PR TITLE
Added AWS credential hook for pre-commit

### PR DESCRIPTION
**Pull request by webbyfox**

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]
LGTM 🚢 🚢 🚢 🚢 🚢

**Review by depsiatwal — COMMENTED** [review]
we could include this as part of test_requirements to force installation just in tests and not prod/staging/dev deployments

**Comment by stevejalim** [comment]
@depsiatwal 
> we could include this as part of test_requirements to force installation just in tests and not prod/staging/dev deployments

the trick would be also running `pre-commmit install --install-hooks` too. We could probably fold that into the makefile command

**Comment by webbyfox** [comment]
Yeah, I will merge this and add another PR for the makefile.

**Comment by depsiatwal** [comment]
> @depsiatwal
> 
> > we could include this as part of test_requirements to force installation just in tests and not prod/staging/dev deployments
> 
> the trick would be also running `pre-commmit install --install-hooks` too. We could probably fold that into the makefile command

ahhh yes good idea

**Comment by webbyfox** [comment]
> pre-commmit install --install-hooks

Adding this... DONT MERGE

**Review by stevejalim — APPROVED** [review]
🌟

**Pull request merged**
